// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI4reetIGZokzQ-jmM_yCeXrQTfExYdgA',
    appId: '1:658614750467:web:28f267e4be63c535282d36',
    messagingSenderId: '658614750467',
    projectId: 'quiz-1155b',
    authDomain: 'quiz-1155b.firebaseapp.com',
    storageBucket: 'quiz-1155b.firebasestorage.app',
    measurementId: 'G-NKS4JS5DB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtec6DVdED5T1sMdVQ5s85T42tUhDcy5U',
    appId: '1:658614750467:android:ca9932c0b7809be2282d36',
    messagingSenderId: '658614750467',
    projectId: 'quiz-1155b',
    storageBucket: 'quiz-1155b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJEjLHB2_Mv0JmXYpanTupbdxNzJYcnnw',
    appId: '1:658614750467:ios:b4d919a39dfe2f1c282d36',
    messagingSenderId: '658614750467',
    projectId: 'quiz-1155b',
    storageBucket: 'quiz-1155b.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJEjLHB2_Mv0JmXYpanTupbdxNzJYcnnw',
    appId: '1:658614750467:ios:b4d919a39dfe2f1c282d36',
    messagingSenderId: '658614750467',
    projectId: 'quiz-1155b',
    storageBucket: 'quiz-1155b.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI4reetIGZokzQ-jmM_yCeXrQTfExYdgA',
    appId: '1:658614750467:web:c220c29d76b2f034282d36',
    messagingSenderId: '658614750467',
    projectId: 'quiz-1155b',
    authDomain: 'quiz-1155b.firebaseapp.com',
    storageBucket: 'quiz-1155b.firebasestorage.app',
    measurementId: 'G-8RB7Q4XW2F',
  );
}
